apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: isodate-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: isodate-service
    spec:
      containers:
      - name: isodate-service
        image: duyushui/isodate-service:latest
        ports:
        - containerPort: 3000
